// Code generated by 'guts'. DO NOT EDIT.

// From rpctypes/types.go
/**
 * DataCreatedEvent - Result for the [EventKindDataCreated] event.
 */
export type DataCreatedEvent = {
    /**
     * The unique identifier for the result
     */
    // this is likely an enum in an external package "github.com/google/uuid.UUID"
    id: string;
};

// From rpctypes/coretypes.go
export type EventKind = "data.created" | "data.updated";

export const EventKinds: EventKind[] = ["data.created", "data.updated"];

// From rpctypes/coretypes.go
export type MethodKind = "ping" | "subscribe" | "unsubscribe" | "user.create" | "user.delete" | "user.get" | "user.list" | "user.update";

export const MethodKinds: MethodKind[] = ["ping", "subscribe", "unsubscribe", "user.create", "user.delete", "user.get", "user.list", "user.update"];

// From rpctypes/types.go
/**
 * PingResult - Result for the [MethodKindPing] method.
 */
export type PingResult = {
    /**
     * A message describing the result
     */
    message: string;
    /**
     * The status of the ping
     */
    status: PingStatus;
};

// From rpctypes/types.go
export type PingStatus = "error" | "success";

export const PingStatuses: PingStatus[] = ["error", "success"];

// From rpctypes/types.go
/**
 * SubscribeParams - Parameters for the [MethodKindSubscribe] method.
 */
export type SubscribeParams = {
    /**
     * The event topic to subscribe to
     */
    event: EventKind;
};

// From rpctypes/types.go
/**
 * SubscribeResult - Result for the [MethodKindSubscribe] method.
 */
export type SubscribeResult = {
    /**
     * Whether the subscribe was successful
     */
    success: boolean;
};

// From rpctypes/types.go
/**
 * UnsubscribeParams - Parameters for the [MethodKindUnsubscribe] method.
 */
export type UnsubscribeParams = {
    /**
     * The event topic to unsubscribe from
     */
    event: EventKind;
};

// From rpctypes/types.go
/**
 * UnsubscribeResult - Result for the [MethodKindUnsubscribe] method.
 */
export type UnsubscribeResult = {
    /**
     * Whether the unsubscribe was successful
     */
    success: boolean;
};

