// Code generated by 'guts'. DO NOT EDIT.

// From rpctypes/types.go
/**
 * DataCreatedEvent - Result for the [EventKindDataCreated] event.
 */
export type DataCreatedEvent = {
    /**
     * The unique identifier for the result
     */
    // this is likely an enum in an external package "github.com/google/uuid.UUID"
    id: string;
};

// From rpctypes/coretypes.go
export enum EventKind {
    /**
     * Only for internal use.
     * You are warned
     */
    EventKindDataCreated = "data.created",
    EventKindDataUpdated = "data.updated"
}

// From rpctypes/coretypes.go
export enum MethodKind {
    MethodKindPing = "ping",
    MethodKindSubscribe = "subscribe",
    MethodKindUnsubscribe = "unsubscribe",
    MethodKindUserCreate = "user.create",
    MethodKindUserDelete = "user.delete",
    MethodKindUserGet = "user.get",
    MethodKindUserList = "user.list",
    MethodKindUserUpdate = "user.update"
}

// From rpctypes/types.go
/**
 * PingResult - Result for the [MethodKindPing] method.
 */
export type PingResult = {
    /**
     * A message describing the result
     */
    message: string;
    /**
     * The status of the ping
     */
    status: PingStatus;
};

// From rpctypes/types.go
export enum PingStatus {
    PingStatusError = "error",
    PingStatusSuccess = "success"
}

// From rpctypes/types.go
/**
 * SubscribeParams - Parameters for the [MethodKindSubscribe] method.
 */
export type SubscribeParams = {
    /**
     * The event topic to subscribe to
     */
    event: EventKind;
};

// From rpctypes/types.go
/**
 * SubscribeResult - Result for the [MethodKindSubscribe] method.
 */
export type SubscribeResult = {
    /**
     * Whether the subscribe was successful
     */
    success: boolean;
};

// From rpctypes/types.go
/**
 * UnsubscribeParams - Parameters for the [MethodKindUnsubscribe] method.
 */
export type UnsubscribeParams = {
    /**
     * The event topic to unsubscribe from
     */
    event: EventKind;
};

// From rpctypes/types.go
/**
 * UnsubscribeResult - Result for the [MethodKindUnsubscribe] method.
 */
export type UnsubscribeResult = {
    /**
     * Whether the unsubscribe was successful
     */
    success: boolean;
};

